version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: copy-fast-dev-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"